### ISSUE TITLE
Add gradients

### ISSUE THREAD

**Issue by rkrasky** [pixijs/pixi-text-style#1]
Please add gradients and make fill colors editable to support rgba or number values.

**Comment by jonlepage** [comment]
+1 for color piker
https://itsjavi.com/bootstrap-colorpicker/
licence m.i.t

**Comment by bigtimebuddy** [comment]
@rkrasky fills are editable now using the `<input type="color">` selector. Note: [not all browsers](http://caniuse.com/#feat=input-color) support this input type.

Will work on gradient support.

**Comment by bigtimebuddy** [comment]
Also, you can now [deep-link](https://pixijs.github.io/pixi-text-style/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.2%2C%22dropShadowAngle%22%3A1%2C%22fill%22%3A%22%23ff3a69%22%2C%22fontFamily%22%3A%22Arial%20Black%22%2C%22fontSize%22%3A70%2C%22miterLimit%22%3A5%2C%22stroke%22%3A%22white%22%2C%22strokeThickness%22%3A5%7D%2C%22background%22%3A%22%235e77c1%22%7D) to settings.

**Comment by bigtimebuddy** [comment]
Added basic gradient support https://goo.gl/F1b528 

The only piece I have yet to implement is `fillGradientStops`, which will probably involve some drag-and-drop.
