### ISSUE TITLE
some proposition

### ISSUE THREAD

**Issue by jonlepage** [pixijs/pixi-text-style#2]
first, thank, your tool are awsome!
i have some sugest,

- **dropShadowAlpha** are not decimal. increase by (0.1)

- **Color piker **  for fill and strok, 
https://itsjavi.com/bootstrap-colorpicker/

- **Add parent and child container** to place pixi.text in a container , for easy see som align and achor engine
able to set bg color for container and widh heigth.
container, not affect the code

**Comment by bigtimebuddy** [comment]
✅  Added 0.1 step to dropShadowAlpha (and to dropShadowAngle)
✅  Added color picker, using `<input type="color">`
✅  Added background color setting

I won't add parent/child container or the background width and height settings. This tool is not for laying out text, only for adjusting and previewing the TextStyle object. 

If you want a tool for doing text layout, I would suggest using a tool I built called PixiAnimate (https://creative.adobe.com/addons/products/14345), which is an exporter for Adobe Animate (which supports text).
