### ISSUE TITLE
Alpha missing ?

### ISSUE THREAD

**Issue by jonlepage** [pixijs/pixi-text-style#3]
I do not know the reason for the problem, but it seems that alpha(rgba) is not present.
Can be a non-compatible webkit?
i try in chrome and Edge.
![aeveee](https://cloud.githubusercontent.com/assets/24865815/26750903/f116a5fe-47fa-11e7-8776-f7002d4425e3.jpg)
![aeffff](https://cloud.githubusercontent.com/assets/24865815/26750912/3c706080-47fb-11e7-912f-8a73d421798e.jpg)

The styles I need to previews its exclusively generate with rgba
I thought maybe could be able to directly modify the code, but the keyboard and the changes are disabled.

Do you have any idea about a possible solution?

I do not know if this idea can seduce you.
You may have a better idea.
![afwcawefef](https://cloud.githubusercontent.com/assets/24865815/26751006/9eb5ece0-47fd-11e7-992d-cbe7438e5033.jpg)

thank a lot , your work are awsomes.

**Comment by bigtimebuddy** [comment]
The problem is that rgba is not supported in Pixi, so I cannot support it in the editor. You'll need to make an issue on the main repo to support these types of values.

However I did realize I'm missing dropShadowColor! I'll add that.

**Comment by jonlepage** [comment]
ho ! ok , i confirm , is because in my node.js project i have a custome pixi.js with ?
``` js 
    /**
     * The background color as a number.
     *
     * @member {number}
     * @private
     */
    _this._backgroundColor = 0x000000;

    /**
     * The background color as an [R, G, B] array.
     *
     * @member {number[]}
     * @private
     */
    _this._backgroundColorRgba = [0, 0, 0, 0];

    /**
     * The background color as a string.
     *
     * @member {string}
     * @private
     */
    _this._backgroundColorString = '#000000';

    _this.backgroundColor = options.backgroundColor || _this._backgroundColor; // run bg color setter
```

So RGBA && RGB are takent with pixi by default.
I am sad not to be able to see rendering in your HTML5 pxi style generator.
thanks anyway

**Comment by jonlepage** [comment]
the lib use are this one ,
https://github.com/rpgtkoolmv/corescript/tree/master/js/libs
see pixi.js

**Comment by jonlepage** [comment]
Thanks, grace to you, now I can observe basic behavior of some base style that I was not understand,now i understant more, thank you infinitely

**Comment by jonlepage** [comment]
Your is much cleaner and more professional.
However, I confess to having a preference for the bootstrap color selector smaller of its design.
and is allow import the json befor to edit , that cool
http://pixitools.jamdonut.com/
If you find good you can draw inspiration from it.
The official page is the following.
http://www.html5gamedevs.com/topic/30731-pixi-text-style-generator/
i credit you
