### ISSUE TITLE
inLine code format

### ISSUE THREAD

**Issue by jonlepage** [pixijs/pixi-text-style#5]
hi frien, this its just a low priority proposition.
Add a case to get code in one line (compressed)

example: 
```javascript
const style = new PIXI.TextStyle({
    dropShadow: true,
    dropShadowAlpha: 0.2,
    dropShadowAngle: 0.4,
    dropShadowBlur: 2,
    dropShadowDistance: 3,
    fill: 'white',
    fontSize: 14,
    letterSpacing: 1,
    lineJoin: 'round',
    strokeThickness: 3
});
```
to a copy past like thats
`var style = new PIXI.TextStyle({ dropShadow: true, dropShadowAlpha: 0.2, dropShadowAngle: 0.4, dropShadowBlur: 2, dropShadowDistance: 3, fill: 'white', fontSize: 14, letterSpacing: 1, lineJoin: 'round', strokeThickness: 3 });`
ok it is voluntary laziness, but it will avoid me to use a compressor for some long codes that I am implanting.
thanks
and gread jobs , your tool are very awsome for me.

**Comment by bigtimebuddy** [comment]
I added support for indent option:
https://pixijs.github.io/pixi-text-style/

You can select the type of indent or choose none.

![screen shot 2017-11-06 at 1 22 14 pm](https://user-images.githubusercontent.com/864393/32457013-89b0a3d0-c2f5-11e7-96c4-f00793aa1360.png)

**Comment by jonlepage** [comment]
omg, thats awsome thank a lot !it's even better than I imagined.
