### ISSUE TITLE
add Filter text preview + code

### ISSUE THREAD

**Issue by jonlepage** [pixijs/pixi-text-style#6]
hi, another small **low priority** suggestion.
Possible to add filter for preview text and maybe get code if possible.
this allows to customize a desired filter effect on text, quickly and save a lot of time to get the desired result and code.

**sketch**:
![filter-preview-code](https://user-images.githubusercontent.com/24865815/32482540-2411346a-c366-11e7-8265-962b2bc83246.jpg)
a suggestion but could also use a float box that we can activate
thank a lot

**Comment by bigtimebuddy** [comment]
This is a little outside the scope of the goal of this project. For the sake of not making this project more complex, I'm going to decline this suggestion. I hope that in the future, we can create a general-purpose PixiJS editor that would allow for text, sprites, filters, asset management.
